<?php
// session_start(); 
?>
<html>
    <body>
        <h2>
            Do login
        </h2>
        <form action="login/random" method="POST">
            <label> Username <input type="text" placeholder="Username..." name="username"></label><br>
            <label> Password <input type="text" placeholder="Password..." name="password"></label><br>
            <input type="submit" name="submit" value="Login">
        </form>
    </body>
</html>
